### ISSUE TITLE
More than one statement per source code line

### ISSUE THREAD

**Issue by s7oev** [SAP/styleguides#145]
This is something that hasn't been discussed in this guide, but the official SAP help states the following:

_Write a maximum of one statement in every source code line._ [(source)](https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenstatement_guidl.htm)

Nevertheless, I think that **not** following this can lead to a much more beautiful code, by creating one-liners where no new syntax (e.g., switch or cond) can handle the situation. Let's look at the following example implementation of an equals() methods in Java for a Point2D class that represents a point in 2-dimensional space, by Robert Sedgewick and Kevin Wayne from Princeton University [(source)](https://algs4.cs.princeton.edu/13stacks/Point2D.java.html):
```
 public boolean equals(Object other) {
    if (other == this) return true;
    if (other == null) return false;
    if (other.getClass() != this.getClass()) return false;
    Point2D that = (Point2D) other;
    return this.x == that.x && this.y == that.y;
}
```
Lets focus on the first two lines:
```
if (other == this) return true;
if (other == null) return false;
```
What would be the equivalent in ABAP? Here's an example (where is_equal is the returning parameter):
```
IF other EQ me.
  is_equal = abap_true.
  RETURN.
ENDIF.

IF other IS NOT BOUND.
  is_equal = abap_false.
  RETURN.
ENDIF.
```
What can (and, in my opinion - should) be accomplished by a oneliner, becomes 4 lines in ABAP. I see two options that can lead to improvement. Option 1 - full one-liner:
```
IF other EQ me. is_equal = abap_true. RETURN. ENDIF.
IF other IS NOT BOUND. is_equal = abap_false. RETURN. ENDIF.
```
Now, this might be controversial and too much non-"abapic". If this is seen as too extreme, I believe that the second option is still a great improvement:
```
IF other EQ me.
  is_equal = abap_true. RETURN.
ENDIF.
IF other IS NOT BOUND.
  is_equal = abap_false. RETURN.
ENDIF.
```
We are effectively emulating the typical behavior of return in most programming languages - i.e., immediate return of a value and thus end of the function, and I see this as one operation. As a result, we save a line that would otherwise be consisting of just the command RETURN.

So, to conclude, I propose that this rule should be reviewed and changed to "use with caution", rather than don't use at all. 

Does anyone have some input with regards to this idea?

**Comment by flaiker** [comment]
I understand your point but I also cannot read both your better ABAP examples "at a glance". There would be some adjustment needed to get used to it.

You also should keep in mind that you cannot F5 step into different statements in the same line in the debugger unless you press the "Debugger step type" button, which does not exist in ADT (or I have not found it).

The missing "return value and return from method" functionality is probably related to methods possibly having more than one parameter that gets returned (-> exporting, changing, tables). So there might be additional operations you need to do after setting the returning parameter.

This reminds me of the discussion of the use of CHECK at the beginning of methods rather than having an IF-statement with an explicit return statement in it.

Thinking about your Java example, wouldn't these be "better"?

```abap
IF other = me.
  is_equal = abap_true.
ELSEIF other IS NOT BOUND.
  is_equal = abap_false.
ELSEIF other->get_class( ) <> get_class( ).
  is_equal = abap_false.
ELSE.
  DATA(that) = CAST point2d( other ).
  is_equal = xsdbool( x = that->x AND y = that->y ).
ENDIF.
```

Or even
```abap
is_equal = COND #(
  WHEN other = me THEN abap_true
  WHEN other IS NOT BOUND THEN abap_false
  WHEN other->get_class( ) <> get_class( ) THEN abap_false
  ELSE LET that = CAST point2d( other ) IN
       xsdbool( that->x = x AND that->y = y )
).
```

**Comment by mAltr** [comment]
Based on  in Clean Code - Robert C. Martin - the mentioned java snipped 

```
if (other == this) return true;
if (other == null) return false;
```
should be

```
if (other == this) 
   return true;
if (other == null) 
   return false;
```

Therefore you are trying to adapt an antipattern in my opinion ;)

**Comment by s7oev** [comment]
Excellent points, and the rewrites proposed by @flaiker are definitely very elegant, readable and short!

And, more importantly, I was not expecting that this might lead to issues with the debugger, nor that Robert C. Martin himself recommended avoiding this.

Thanks for considering the input, I'm closing the issue.

**Comment by jordao76** [comment]
@mAltr I am not able to find the place in the book Clean Code where that is specifically mentioned. Can you point out the section?

Nevertheless, I see _guard clauses_ as a perfectly valid idiom, and I implement them in one line and without brackets in languages that have brackets. I wrote about it [here](https://stackoverflow.com/a/8021329/31158). There's a refactoring about it [here](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).

In an ABAP `IF` statement it doesn't make sense because you'd need that awkward `ENDIF` at the end of the statement. You can still use `CHECK` though.

**Comment by mAltr** [comment]
@jordao76 "Blocks and Indenting" page 35 and "Intendation" page 88

He also describes later in page 90, the temptation to ignore the indentation rule for short if and while statements.

**Comment by jordao76** [comment]
Thanks!

I still think there are situations, namely _guard clauses_, that would be fine in one line. Not in ABAP though.
