### ISSUE TITLE
Chaining attributions. How about it? Good or bad practice?

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [SAP/styleguides#217]
Should this be allowed or is it considered a bad behavior? 
var1 = var2 = var3 = cl=>method( ).

A real case though:
lo_cell = lo_cell->cdr = lcl_lisp_new=>cons( io_car = lo_peek ).

ABAP Lint considers this to be a bad practice in all cases (independent of the type of variable): "...In my opinion: avoid using chained assignment in all cases, its rarely used in actual code, and easy to work around..."

Thus, our question is: Should this rule be applied only for boolean types where XSDBOOL should be used instead OR to any kind of variable (all types). 

What is your opinion? We raised this issue due to another issue we have:
https://github.com/SAP/code-pal-for-abap/issues/398

Our opinion: This should be applied to all variable types (as ABAP Lint does). We could have one CHECK for chaining bool types (where we should use XSDBOOL) and another check (similar) for all types of variables (or even a single check with a customizing checkbox: Apply only to Boolean Type Variables?)

thank you for your input!!

**Comment by pokrakam** [comment]
I agree with discouraging it altogether. It's inconsistent to have a rule that applies partially; and I don't see the potential for confusion limited to booleans, because you could assign a boolean result to any `clike` datatype.

On the other hand ABAP doesn't support boolean evaluation in the form of `a = ( b = c ).`, so one could also argue there is no potential for confusion, but personally I think it's not always that obvious at first glance and prefer to just sidestep the whole thing. 

Also inline `data(x)` doesn't work in any position of a multiple assignment (had to try this one out 🙂)
