### ISSUE TITLE
Prefixes in identifiers

### ISSUE THREAD

**Issue by flaiker** [SAP/styleguides#48]
I'd like to comment on the suggestions to drop variable and parameter prefixes entirely.
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#avoid-encodings-esp-hungarian-notation-and-prefixes

While I personally like my prefixes just because I got used to them in my opinion this is a valid recommendation that one can decide on to follow. Especially because of the length limitations in ABAP for everything, so you get more space to describe things. I would however argue that if you already have an existing code base that follows some kind of prefixing naming convention (like the SAP one in the code inspector...) it is worse to write new code without prefixes than to just follow your existing guideline.  The advantage of having no prefixes at all is very minor (neglectable) compared to having a consistent code base, in my opinion.

And by the way:
`Other languages like Java use absolutely no prefixes, and still Java code is perfectly readable.`

One notable exception is the Android Open Source Project, which is written in Java and uses prefixes for static and member variables:
https://source.android.com/setup/contribute/code-style#follow-field-naming-conventions

It violates the current Google Java Style Guide

https://google.github.io/styleguide/javaguide.html#s5.1-identifier-names

While the opinion might have changed on this topic they keep their convention because to them consistency is more important:

> Our parting thought: BE CONSISTENT. If you're editing code, take a few minutes to look at the surrounding code and determine its style. If that code uses spaces around the if clauses, you should too. If the code comments have little boxes of stars around them, make your comments have little boxes of stars around them too.
> 
> The point of having style guidelines is to have a common vocabulary of coding, so people can concentrate on what you're saying, rather than on how you're saying it. We present global style rules here so people know the vocabulary, but local style is also important. If the code you add to a file looks drastically different from the existing code around it, it throws readers out of their rhythm when they go to read it. Try to avoid this.

https://source.android.com/setup/contribute/code-style#be-consistent

(Also since Java accounts for lower and upper case code constants (static final) have the convention of being all upper case and separated by underscore which is sort of a naming convention that just does not compare to ABAP in the same way for obvious reasons.)

Feel free to close this issue, just wanted to comment.

**Comment by tricktresor** [comment]
I am also not really happy with the recommendation of not using any prefixes anymore... In my own daily work I realized, that I often mix prefixing and non-prefixing, depending on something I still have to find out. 

Although methods should be short, due to many reasons, it's not like that in my productive code. If the method is really short I intend to use no prefixes because it simply makes the short code even shorter and therefore better understandable. 
If there is some more logic in the code, I like to have importing parameters named with I_, exporting parameters named with E_ and local or global variables named with L or G/M. I don't know really why. Maybe because I am used to that for so many years and it's not easy to adapt to new things...? 

The other prefix, that tells the type of a variable, makes me also often feel more comfortable with the code. Yes, you often can describe by the name if it's an internal table or a variable, but sometimes you can't (if there is some description with INFORMATION or DATA for example).
It's the same issue when looping over the returning parameter of a function
`LOOP AT order->get_order_items( ) INTO order_item`
It kind of makes me understand the command again and again. Even though I know what it does, it takes more time to interpret.

Plus: I just also like to see if the "thing" is an object, a variable, a table or a work area.

**Comment by HrFlorianHoffmann** [comment]
In response to flaiker's original comments, created the Pull Request _Be consistent_ https://github.com/SAP/styleguides/pull/51. I repeatedly heard this chain of argumentation and think it is a valuable addition.

**Comment by flaiker** [comment]
Fixed in #51
