### ISSUE TITLE
chained data declarations contradiction

### ISSUE THREAD

**Issue by tricktresor** [SAP/styleguides#50]
Hi there!

these two sections are inconsistent with one another:
1. [do not chain-up front declarations](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#do-not-chain-up-front-declarations)
2. [Optimize for reading, not for writing](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#optimize-for-reading-not-for-writing)

In the first section you declare chaining-up data declarations as bad code.
In the 2nd section you say, one should prefer colon separated data declarations.

Due to refactoring issues I am absolutely with the recommendation to use single data statements for each declaration.

Maybe we should find a better example for readable code?!

Cheers
Enno

**Comment by pokrakam** [comment]
I see what you mean, but don't see it as a recommendation, more like "if you're going to use chaining, then at least do it this way", because both versions use chaining. 

So I guess the challenge is: what other coding styles are purely for the sake of ease of editing?Personally I can't think of any better examples than the awful comma-first style. 

In fact, the anti-pattern example is wrong, it should have the fullstop on its own line at the end.
```ABAP
data: a type c
    , b type c
    , c type c
    .
```
(can you tell I worked with people who were fanatical about this?)

**Comment by vonglan** [comment]
Yes, I also think Mike's anti-pattern is better.
By the way, I noticed that if you use the Pretty Printer, you spend more useless manual editing time (that you want to avoid), if you use the "comma first" notation.
Because the Pretty Printer assumes the "comma at the end" notation, and some automatic indentation only works in this case.
