### ISSUE TITLE
Consider converting legacy messages into class exceptions

### ISSUE THREAD

**Issue by nununo** [SAP/styleguides#65]
I like to convert all MESSAGEs (coming out of Function Modules or other legacy code) into class exceptions. This way everything is handled in the same way.

In order to accomplish this, my root exceptions are extended with the following functionality:

1. An extra bool attribute called MESSAGE_FROM_SYST
2. A local class which is will hold the SYST message data:
```
class lcx_t100_syst definition inheriting from cx_dynamic_check final.
  public section.
    interfaces if_t100_message.
    methods constructor.
    data msgv1 type symsgv.
    data msgv2 type symsgv.
    data msgv3 type symsgv.
    data msgv4 type symsgv.
endclass.                    "cx_t100 DEFINITION

class lcx_t100_syst implementation.
  method constructor.
    super->constructor( ).
    me->msgv1 = sy-msgv1.
    me->msgv2 = sy-msgv2.
    me->msgv3 = sy-msgv3.
    me->msgv4 = sy-msgv4.
    if_t100_message~t100key-msgid = sy-msgid.
    if_t100_message~t100key-msgno = sy-msgno.
    if_t100_message~t100key-attr1 = 'MSGV1'.
    if_t100_message~t100key-attr2 = 'MSGV2'.
    if_t100_message~t100key-attr3 = 'MSGV3'.
    if_t100_message~t100key-attr4 = 'MSGV4'.
  endmethod.                    "constructor
endclass.                    "cx_t100 IMPLEMENTATION
```
3. An extra method `BUILD_FROM_SYST()` in the ZCX class:
```
method BUILD_FROM_SYST.
  DATA: o_exp TYPE REF TO lcx_t100_syst.
  IF me->previous IS NOT BOUND AND me->message_from_syst = abap_true.
    TRY .
        RAISE EXCEPTION TYPE lcx_t100_syst.
      CATCH lcx_t100_syst INTO o_exp.
        me->previous = o_exp.
    ENDTRY.
  ENDIF.
endmethod.
```
4. Add an _enhancement_ to the `CONSTRUCTOR` so that it calls `BUILD_FROM_SYST()`:
```
method CONSTRUCTOR.
(...)
ENHANCEMENT 1  ZCX_ROOT.    "active version
  build_from_syst( ).
ENDENHANCEMENT.
endmethod.
```

Maybe this is too convoluted and beyond the scope of this guide. If so please just go head and close it.

**Comment by flaiker** [comment]
With 750 and up you get a native syntax for raising exceptions with messages so I am not sure this fits the guide.
[IF_T100_DYN_MESSAGE](https://help.sap.com/doc/abapdocu_753_index_htm/7.53/en-US/index.htm?file=abenif_t100_dyn_msg.htm)
[RAISE EXCEPTION TYPE cx_demo_dyn_t100 USING MESSAGE.](https://help.sap.com/doc/abapdocu_753_index_htm/7.53/en-US/index.htm?file=abapraise_exception_message.htm)

By the way, if you are on at least 740 you don't need an enhancement because you can just edit exception class constructors in ADT (I assume that's the reason?). [Similar logic for 740](https://github.com/flaiker/ci-lib/blob/master/src/zcx_cilib_static_check.clas.abap)

**Comment by nununo** [comment]
Hi @flaiker, 

Indeed the system I'm currently working on has yet to be upgraded to 740 :(

But I'm happy that this crazy solution is no longer needed so I'll just go ahead and close this ticket and eagerly wait for my system to be upgraded. 

Thanks!!
