### ISSUE TITLE
Consider using immutable instead of getter

### ISSUE THREAD

**Issue by openPhiL** [SAP/styleguides#78]
Hi, 
I prefer getter over immutables in cases like this: 

```
is_new_version_active
        RETURNING
          VALUE(rv_is_active) TYPE abap_bool,
```

In this case, I can use 
`IF object->is_new_version_active()`
vs (for immutables):
`IF object->is_new_version_active = ABAP_TRUE`

which I think is easier on the eye. 

What do you guys think? 
PhiL

**Comment by HrFlorianHoffmann** [comment]
We all agree that `IF object->is_active( )` is easier on the eye than the repetitive `IF object->is_active = abap_true`.

On the other hand, consider the overhead of adding getters. The few characters you save in the conditions you spend several times over in the definition and implementation of the repetitive getters.

Doing this exclusively for Boolean attributes is questionable, as it mixes up different styles in the same class. Your co-developers will probably ask you to add getters for all 42 attributes, not only the 3 Boolean ones, for symmetry and clarity. For non-Boolean attributes, you will not be able to avoid the comparison value, such that getters will not provide any benefit.

The section [Consider using immutable instead of getter](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#consider-using-immutable-instead-of-getter) deliberately says "consider" to leave this choice to you.

The best choice of course would be to allow `IF object->is_active` right away, if `is_active` has a clearly Boolean data type.

**Comment by openPhiL** [comment]
That is a good explanation, thanks! Will keep that in mind. 
Allowing `IF object->is_active`  would be great. I guess it is coming eventually.
